### ISSUE TITLE
VO model training

### ISSUE THREAD

**Issue by AshwiniUthir** [Xiaoming-Zhao/PointNav-VO#10]
Can you please let me know how long does it take for the VO model training to run (with default configurations)? How long does it take to create 1 checkpoint?

**Comment by Xiaoming-Zhao** [comment]
It largely depends on the size of your generated dataset. For the 1-million-entry dataset we used in the paper, it needs 4-5 days to complete the whole training on a GeForce RTX 2080 Ti.

Please follow this guidance: https://github.com/Xiaoming-Zhao/PointNav-VO/blob/main/TRAIN.md

It takes around 1.5 hours to complete one epoch and save the checkpoint at the end of each epoch. If you want more intermediate results, you can use the following line to achieve your goal by setting up your preferred logging interval.
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/eb509b13234bba3ede81c1c5b96a46cf0c39e069/pointnav_vo/vo/engine/vo_cnn_regression_geo_invariance_engine.py#L1018

**Comment by AshwiniUthir** [comment]
Thank you for the quick response. Can you also please let me know how long does it take for the Navigation policy training to run and how long does it take to create 1 checkpoint ?

**Comment by Xiaoming-Zhao** [comment]
It depends on how many GPUs you want to parallelize the training with. IIRC, for one GPU, it takes 2 or 3 days to get a reasonable success rate or SPL. 4 or 5 days may be better. I have detailed logging in the tensorboard, you can observe it.

For saving checkpoints, I remember it will save around half an hour. You can set up the saving interval here: 
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/eb509b13234bba3ede81c1c5b96a46cf0c39e069/pointnav_vo/rl/ddppo/algo/ddppo_trainer.py#L605
