### ISSUE TITLE
Multi GPU training not working

### ISSUE THREAD

**Issue by Praneethcruzon** [Xiaoming-Zhao/PointNav-VO#15]
Multi GPU training on VO model is broken/not working. The argument n-gpu simply doesnt do anything. Tweaking the code to run on multiple GPU using pytorch parallelism also doesnt work. We had the scripts hung indefinitely, seems to be resource allocation issues. 

Is there a possibility of running VO model training across multiple GPUs? We could really make use of it to speed it up.

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for your interest in this work. Unfortunately, the VO training does not support multi-GPU training yet. I was trying to make that but have not got time to do it. You may have to refactor the code a little bit if you need multiple GPU training. Sorry about that.

**Comment by Praneethcruzon** [comment]
That's unfortunate. We also tried to run multiple training in parallel with cloning the datasets/vo_datasets into multiple copies. But even then the training was stopped with the following error:

Traceback (most recent call last):
  File "./pointnav_vo/run.py", line 347, in <module>
    main()
  File "./pointnav_vo/run.py", line 75, in main
    run_exp(**vars(args))
  File "./pointnav_vo/run.py", line 313, in run_exp
    trainer.train()
  File "/home/praneeth/PointNav-VO/pointnav_vo/vo/engine/vo_cnn_regression_geo_invariance_engine.py", line 841, in train
    batch_data = next(train_iter)
  File "/home/praneeth/anaconda3/envs/pointnav-vo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/praneeth/anaconda3/envs/pointnav-vo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/praneeth/anaconda3/envs/pointnav-vo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 928, in _get_data
    raise RuntimeError('DataLoader timed out after {} seconds'.format(self._timeout))
RuntimeError: DataLoader timed out after 300 seconds


Initially we thought, this might be because both the training are accessing the same dataset, since the dataset is not loaded into the memory. And that is the why we cloned the dataset in first place. pointing dataset1 for one training and dataset2 for another training. We made these changes in configs/vo/vo_pointnav.yaml config file. But even then we faced the same issue. and the training was stopped after some epochs. 

Do you think is there a change wherein the config file is also not stored in memory and its being read after every epochs? Or do you feel is there anything in the code that might cause this error? 

I'd like to know what we should do if we need to run multiple trainings parallel, with one GPU allocated to each training.

**Comment by Xiaoming-Zhao** [comment]
Close as the discussion has been moved to #16
