### ISSUE TITLE
Parallel training Not working

### ISSUE THREAD

**Issue by Praneethcruzon** [Xiaoming-Zhao/PointNav-VO#16]
We tried to run multiple training in parallel with cloning the datasets/vo_datasets into multiple copies. But even then the training was stopped with the following error:

Traceback (most recent call last):
File "./pointnav_vo/run.py", line 347, in
main()
File "./pointnav_vo/run.py", line 75, in main
run_exp(**vars(args))
File "./pointnav_vo/run.py", line 313, in run_exp
trainer.train()
File "/home/praneeth/PointNav-VO/pointnav_vo/vo/engine/vo_cnn_regression_geo_invariance_engine.py", line 841, in train
batch_data = next(train_iter)
File "/home/praneeth/anaconda3/envs/pointnav-vo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in next
data = self._next_data()
File "/home/praneeth/anaconda3/envs/pointnav-vo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
idx, data = self._get_data()
File "/home/praneeth/anaconda3/envs/pointnav-vo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 928, in _get_data
raise RuntimeError('DataLoader timed out after {} seconds'.format(self._timeout))
RuntimeError: DataLoader timed out after 300 seconds

Initially we thought, this might be because both the training are accessing the same dataset, since the dataset is not loaded into the memory. And that is the why we cloned the dataset in first place. pointing dataset1 for one training and dataset2 for another training. We made these changes in configs/vo/vo_pointnav.yaml config file. But even then we faced the same issue. and the training was stopped after some epochs.

Do you think is there a change wherein the config file is also not stored in memory and its being read after every epochs? Or do you feel is there anything in the code that might cause this error?

I'd like to know what we should do if we need to run multiple trainings parallel, with one GPU allocated to each training.

**Comment by Xiaoming-Zhao** [comment]
Are you having several independent trainings or those trainings are related?

**Comment by Praneethcruzon** [comment]
Trainings are independed,, like one with resnet18 another with resnet50. But they should make use of same data and source code.

**Comment by Xiaoming-Zhao** [comment]
My suspicion is that this may be related to OpenCV. See comment here:
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/eb509b13234bba3ede81c1c5b96a46cf0c39e069/pointnav_vo/vo/dataset/regression_geo_invariance_iter_dataset.py#L251

Maybe you can try to set `multiprocessing` to use `spawn`:
```
import multiprocessing
multiprocessing.set_start_method('spawn')
import torch
torch.multiprocessing.set_start_method('spawn')
```
