### ISSUE TITLE
Vadilation Results

### ISSUE THREAD

**Issue by Gowthamsid2799** [Xiaoming-Zhao/PointNav-VO#17]
Where can i find the video results after the validation ?

**Comment by Xiaoming-Zhao** [comment]
You can set this line to be `["disk"]` and run evaluation again:
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/eb509b13234bba3ede81c1c5b96a46cf0c39e069/configs/rl/ddppo_pointnav.yaml#L18
