### ISSUE TITLE
An error is reported when the pre-training file of the VO model is loaded

### ISSUE THREAD

**Issue by 200203Z** [Xiaoming-Zhao/PointNav-VO#18]
When I perform   
pathfile='pretrained_ckpts/vo/act_forward.pth'
pretrained_ckpt = torch.load(pathfile) 
This error occurs：AttributeError: Can't get attribute 'Config' on <module 'habitat.config.default' from '/root/autodl-tmp/habitat-lab-0.2.3/habitat-lab/habitat/config/default.py'>
Is my habitat version (0.2.3) wrong, what is the habitat version used by the author? How should I install it? How to solve the problem with the pre-training file.Thank you!

**Comment by Xiaoming-Zhao** [comment]
I think `0.2.3` may be too new. 

The specific commits of habitat-lab/sim are specified here: https://github.com/Xiaoming-Zhao/PointNav-VO#install-habitat

**Comment by 200203Z** [comment]
Thank you for your reply, but when I open the habitat corresponding to install-habitat, it goes to the latest version (0.3.0) github interface, and I can't be sure of the specific version.

**Comment by Xiaoming-Zhao** [comment]
You can specify the commit in the url:
- https://github.com/facebookresearch/habitat-lab/tree/d0db1b55be57abbacc5563dca2ca14654c545552#installation
- https://github.com/facebookresearch/habitat-sim/tree/020041d75eaf3c70378a9ed0774b5c67b9d3ce99#installation

Pay attention to the commit ID after `tree`.
