### ISSUE TITLE
Evaluation with noise-free sensors

### ISSUE THREAD

**Issue by StOnEGiggity** [Xiaoming-Zhao/PointNav-VO#5]
Hi,

Thanks for your work~

Did you evaluate the provided model with noise-free sensors (e.g., GaussianNoiseModel in RGB ) or GPS+Compass sensor? Because I found unsatisfactory results after I did this, which confused me a lot.
Is there any explanation or something I did wrong? Thanks a lot~

**Comment by Xiaoming-Zhao** [comment]
Hi, I did not try the provided models on "clean" sensor data. However, I can expect it to fail as noise-free and noisy data have drastically different data distributions. Therefore, the image encoder for the VO model should learn different features. You may need to train your own version of VO for the clean dataset. Hope this helps.

**Comment by StOnEGiggity** [comment]
Thanks a lot!
