### ISSUE TITLE
Unserstanding of accumulated prediction error

### ISSUE THREAD

**Issue by AgentEXPL** [Xiaoming-Zhao/PointNav-VO#6]
Thanks a lot for sharing this great work. I have doubts on the following thing. 
From my understanding, the visual odometry module is used for estimating the transformation H(Ct -> Ct+1) for one step, and the estimation error does exist. 
If we test the pre-trained model under a trajectory consisting of N steps, the estimation error in step 0 may affect the prediction error in step 1, 2,3,...,N-1. It seems to be that a bigger estimation error will be achieved at a bigger step number. 
Is this correct? In your test experiments, is there any phenomenons to demonstrate this claim?

**Comment by Xiaoming-Zhao** [comment]
In general, your thinking is right, and such a drift problem is a long-standing issue in the field of VO. Actually, you can see from the qualitative figures in the paper, red and blue paths deviate more apparently when the agent moves longer. Hope this helps.

**Comment by AgentEXPL** [comment]
Got it, thanks for your explanation.
