### ISSUE TITLE
vo_pointnav.yaml missing

### ISSUE THREAD

**Issue by fengdai1234** [Xiaoming-Zhao/PointNav-VO#7]
# set pretrained to True if you want to fine-tune some checkpoints
    pretrained: False
    pretrained_ckpt: {
      "forward": "ckpt_forward.pth",
      "left": "act_left.pth",
      "right": "act_right.pth",
    }

Hi Xiaoming,
  It seems like this checkpoint are missing from the repo, could you add that ?

Thanks

**Comment by Xiaoming-Zhao** [comment]
Hi, the provided checkpoint `act_left_right_inv_joint.pth` contains both `turn_left` and `turn_right` models. To use them, you just need to have the following setup:
```
pretrained_ckpt: {
  "forward": "ckpt_forward.pth",
  "left": "act_left_right_inv_joint.pth",
  "right": "act_left_right_inv_joint.pth",
}
```
Hope this helps.
