### ISSUE TITLE
Recreating pertained checkpoints

### ISSUE THREAD

**Issue by AshwiniUthir** [Xiaoming-Zhao/PointNav-VO#8]
How can I recreate the pretrained_ckpts for rl and vo that you have provided (rl_no_tune.pth, rl_tune_vo.pth, act_forward.pth, act_left_right_inv_joint.pth)? When I retrained the rl network, it created more than one hundred checkpoints (I manually stopped it at 103). Where can I specify the number of checkpoints to be created ?

**Comment by Xiaoming-Zhao** [comment]
You can specify the `CHECKPOINT_INTERVAL` to the frequency you prefer.
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/49bbcfe4d4d54b85e740050d34310cf125a85d46/configs/rl/ddppo_pointnav.yaml#L20

**Comment by AshwiniUthir** [comment]
Thank you for the quick response. How can I recreate the pertained_ckpts for both vo and rl that is provided with this code?

**Comment by Xiaoming-Zhao** [comment]
This instruction may be helpful: https://github.com/Xiaoming-Zhao/PointNav-VO/blob/main/TRAIN.md
